road(faerun,tristram,65).
road(faerun,tambi,129).
road(faerun,norrath,144).
road(faerun,snowdin,71).
road(faerun,straylight,137).
road(faerun,alphacentauri,3).
road(faerun,arbre,149).
road(tristram,tambi,63).
road(tristram,norrath,4).
road(tristram,snowdin,105).
road(tristram,straylight,125).
road(tristram,alphacentauri,55).
road(tristram,arbre,14).
road(tambi,norrath,68).
road(tambi,snowdin,52).
road(tambi,straylight,65).
road(tambi,alphacentauri,22).
road(tambi,arbre,143).
road(norrath,snowdin,8).
road(norrath,straylight,23).
road(norrath,alphacentauri,136).
road(norrath,arbre,115).
road(snowdin,straylight,101).
road(snowdin,alphacentauri,84).
road(snowdin,arbre,96).
road(straylight,alphacentauri,107).
road(straylight,arbre,14).
road(alphacentauri,arbre,46).
